name: release-please

on:
    push:
        branches:
            - master

permissions:
    contents: write
    pull-requests: write
    id-token: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: google-github-actions/release-please-action@v4
              id: release
              with:
                  manifest-file: .github/.release-please-manifest.json
                  config-file: .github/release-please-config.json

            - if: ${{ steps.release.outputs.release_created }}
              uses: actions/checkout@v4

            - if: ${{ steps.release.outputs.release_created }}
              uses: actions/setup-node@v4
              with:
                  node-version-file: ".nvmrc"
                  registry-url: "https://registry.npmjs.org"

            - if: ${{ steps.release.outputs.release_created }}
              run: |
                  npm ci &&
                  npm run build &&
                  npm publish --provenance --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
